version: "3.3"

services:
  backend:
    container_name: backend
    ports:
    - 8000
    image: jozenstar/devops-challenge:${TAG}
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: simple_web_app/backend
  web:
    image: nginx
    ports:
    - 80:80
    volumes:
    - ./nginx/mysite.conf:/etc/nginx/conf.d/default.conf
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: simple_web_app/nginx