version: "3.3"

services:
  backend:
    container_name: backend
    ports:
    - 8000
    image: jozenstar/devops-challenge:${TAG}
  web:
    image: nginx
    ports: 
    - 80:80
    volumes: 
    - ./nginx/mysite.conf:/etc/nginx/conf.d/default.conf
